name: KingMonster
version: '${project.version}'
main: bazu.kingmonster.KingMonster
api-version: 1.17
authors: [ bazu ]
commands:
  winItem:
    permission: op

  broadItem:
    permission: op

  findItem:
    permission: op

